name: build-and-push
on: [push]

env:
  IMAGE_NAME: scarecrow928/nginx
  IMAGE_TAG: alpine

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"